Repository UncreativeGames/captain-cleiton, pull requests merged in 2018-05, with the labels that each got.

#22 Floor generation now can be used in game
  examples/DrawingModule_exemplo/main.cpp
  examples/DrawingModule_exemplo/makefile
  examples/DrawingModule_exemplo/player.png
  examples/Floor_example/main.cpp
  include/Floor.h
  include/Floor.hpp
  src/Floor.cpp
  src/TileMap.cpp
Labels: enhancement

#33 Um pequeno passo para o jogo, mas um grande passo para a primeira entrega!
  examples/DrawingModule_exemplo/main.cpp
  examples/DrawingModule_exemplo/makefile
  examples/DrawingModule_exemplo_2/main.cpp
  examples/DrawingModule_exemplo_2/makefile
  examples/DrawingModule_exemplo_2/player.png
  include/Chao.hpp
  include/ColisionModule.hpp
  include/DrawingModule.hpp
  include/Lista.hpp
  include/Listaestatica.hpp
  src/Chao.cpp
  src/ColisionModule.cpp
  src/DrawingModule.cpp
  src/Rigidbody.cpp
Labels: Blocker, Lindo, enhancement, gameengine

#37 Problema de vazamento de memória resolvido
  include/Lista.hpp
Labels: bug

#38 Created Config.hpp
  include/Config.hpp
  include/Floor.hpp
  include/Lista.hpp
  include/Listaestatica.hpp
  include/TileMap.hpp
Labels: enhancement

#42 Módulos refatorados
  examples/DrawingModule_exemplo_2/main.cpp
  include/ColisionModule.hpp
  include/DrawingModule.hpp
  src/ColisionModule.cpp
  src/DrawingModule.cpp
Labels: Blocker

#44 Player não é printado na extremidade inferior
  src/DrawingModule.cpp
Labels: bug

#45 :wip: MapModule funcional
  .gitignore
  CMakeLists.txt
  cmake_modules/FindSFML.cmake
  examples/DrawingModule_exemplo_2/main.cpp
  examples/DrawingModule_exemplo_2/makefile
  examples/Floor_example/main.cpp
  include/Config.hpp
  include/DrawingModule.hpp
  include/Floor.hpp
  include/MapModule.hpp
  src/DrawingModule.cpp
  src/Floor.cpp
  src/MapModule.cpp
  src/TileMap.cpp
Labels: enhancement, module

#47 Mudanças na colisão com as paredes
  examples/DrawingModule_exemplo_2/main.cpp
  examples/DrawingModule_exemplo_2/makefile
  include/Rigidbody.hpp
  include/SquareObstacle.hpp
  include/Wall.hpp
  src/ColisionModule.cpp
  src/MapModule.cpp
  src/Rigidbody.cpp
  src/SquareObstacle.cpp
  src/Wall.cpp
Labels: Lindo, bug, enhancement, gameengine

#51 WIP: Movimentação pelo floor iniciada
  .gitignore
  examples/DrawingModule_exemplo_2/exemplo
  examples/DrawingModule_exemplo_2/main.cpp
  examples/DrawingModule_exemplo_2/makefile
  include/Config.hpp
  include/Floor.hpp
  include/MapModule.hpp
  include/Rigidbody.hpp
  include/SquareObstacle.hpp
  include/TileMap.hpp
  include/Wall.hpp
  src/ColisionModule.cpp
  src/DrawingModule.cpp
  src/Floor.cpp
  src/MapModule.cpp
  src/Rigidbody.cpp
  src/SquareObstacle.cpp
  src/TileMap.cpp
  src/Wall.cpp
Labels: enhancement

#58 Merge consertado e bug de colisão "evitado"
  examples/DrawingModule_exemplo_2/Tile.png
  examples/DrawingModule_exemplo_2/a1floor.png
  examples/DrawingModule_exemplo_2/cave.png
  examples/DrawingModule_exemplo_2/exemplo
  examples/DrawingModule_exemplo_2/makefile
  examples/DrawingModule_exemplo_2/player.png
  include/ColisionModule.hpp
  include/Rigidbody.hpp
  include/SquareObstacle.hpp
  include/Wall.hpp
  src/ColisionModule.cpp
  src/MapModule.cpp
  src/Rigidbody.cpp
  src/SquareObstacle.cpp
  src/Wall.cpp
Labels: bug

#60 Criado GUI
  .gitignore
  Credits.md
  examples/DrawingModule_exemplo_2/exemplo
  examples/DrawingModule_exemplo_2/main.cpp
  examples/DrawingModule_exemplo_2/makefile
  include/Floor.hpp
  include/Gui.hpp
  include/MapModule.hpp
  src/Floor.cpp
  src/Gui.cpp
  src/MapModule.cpp
Labels: enhancement, gameengine, module

#61 Bug de colisão arrumado
  examples/DrawingModule_exemplo_2/exemplo
  include/ColisionModule.hpp
  src/ColisionModule.cpp
  src/MapModule.cpp
Labels: bug

#65 Inimigo simples criado
  .gitignore
  Credits.md
  examples/DrawingModule_exemplo/main.cpp
  examples/DrawingModule_exemplo/makefile
  examples/DrawingModule_exemplo/player.png
  include/ColisionModule.hpp
  include/Config.hpp
  include/DrawingModule.hpp
  include/EnemiesModule.hpp
  include/EnemyBat.hpp
  include/MapModule.hpp
  include/Monster.hpp
  include/TextModule.hpp
  include/TileMap.hpp
  main.cpp
  makefile
  src/ColisionModule.cpp
  src/DrawingModule.cpp
  src/EnemiesModule.cpp
  src/EnemyBat.cpp
  src/Gui.cpp
  src/MapModule.cpp
  src/Monster.cpp
  src/TextModule.cpp
  src/TileMap.cpp
Labels: Data Structure, enhancement
