Repository UncreativeGames/captain-cleiton, pull requests merged in 2018-04, with the labels that each got.

#4 Adicionada classe Obstacle
  Obstacle.cpp
  Obstacle.hpp
  Rigidbody.cpp
  Rigidbody.hpp
Labels: gameengine

#12 Template para lista estática criado
  Listaestatica.hpp
Labels: Blocker, Data Structure

#14 Estrutura que gera os mapas/salas está funcional
  Documentation/Floor.md
  Documentation/TileMap.md
  Floor.cpp
  Floor.h
  TileMap.cpp
  TileMap.h
  TileMap.hpp
  main.cpp
Labels: Blocker, Data Structure

#20 Projeto organizado e novas classes criadas
  exemple/DrawingModule_exemplo/main.cpp
  exemple/DrawingModule_exemplo/makefile
  exemple/DrawingModule_exemplo/player.png
  include/AnimatedSprite.hpp
  include/Animation.hpp
  include/DrawTransform.hpp
  include/DrawingModule.hpp
  include/Floor.h
  include/Lista.hpp
  include/Listaestatica.hpp
  include/Obstacle.hpp
  include/Rigidbody.hpp
  include/TileMap.hpp
  src/AnimatedSprite.cpp
  src/Animation.cpp
  src/DrawTransform.cpp
  src/DrawingModule.cpp
  src/Floor.cpp
  src/Obstacle.cpp
  src/Rigidbody.cpp
  src/TileMap.cpp
Labels: Blocker, enhancement, gameengine
